name: stylua Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run styLua style check for lua programs.
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
